[env]
UV_NO_MODIFY_PATH = 1
UV_INSTALL_DIR_NAME = "bin"
HOME_NAME = "opt"

SITE_CONFIG_DIR = "{SITE_CONFIG_DIR}"

N_PROCS = 8

[install]
versions = ["stable"]
prefix = "{SITE_DESTINATION}"
# note: this is Lua regex: you will need to escape - and + (using %)
format = "^{STAGE_DIR}$"
# (optional) relocate after install
destination = "{SITE_DESTINATION}/{INSTALL_VERSION_VARIANT}"
stage = true

[module]
UV_TOOL_SCRIPTS_DIR = "{INSTALL_DIR}/opt/bin"
UV_TOOL_BIN_DIR = "{INSTALL_DIR}/bin"
UV_TOOL_DIR = "{INSTALL_DIR}/opt"
UV_CONCURRENT_INSTALLS = 8
UV_CONCURRENT_BUILDS = 8

[post]
# toggles mandatory relocate if `stage` and `clean` are true. If the install
# script already relocates the package, then we can set `safe = false`
safe = true
# delete staging aread after successful install
clean = true
