module load zig/${INSTALL_VERSION}

OS=$(to_lower "$RUNTIME_OS")
ARCH=$(to_lower "$RUNTIME_ARCH")

# zig spells arches its own way
[[ $ARCH == "arm64" ]] && ARCH="aarch64"
[[ $ARCH == "amd64" ]] && ARCH="x86_64"

# The one target every shim passes. Naming it explicitly -- instead of letting
# zig target the host -- is what buys the two properties this module is for:
#   * linux: `gnu.<floor>` makes zig link against its bundled glibc stubs of
#     exactly that version, so the binaries run on every host with that glibc
#     or newer, whatever the build host has. zig carries the glibc headers as
#     well, so no libc6-dev is needed anywhere.
#   * macOS: an explicit target makes zig use its bundled libSystem instead of
#     the SDK's .tbd stubs, which zig 0.15+ rejects for the native target
#     (the trick from ncdu/sm-config-build/install.sh) -- so no Xcode either.
# The price is hermeticity: zig then searches none of the host's include or
# library directories. That is the right default on a host without dev
# packages; where host libraries are wanted, -I/-L name them explicitly.
case ${OS} in
    linux)  TARGET="${ARCH}-linux-gnu.${GLIBC_FLOOR}" ;;
    darwin) TARGET="${ARCH}-macos" ;;
    *)
        echo "cc: no shim target for '${OS}/${ARCH}' -- this recipe knows linux (glibc) and darwin"
        exit 1
        ;;
esac

# The zig of the module loaded above, baked in by absolute path: the shims
# then always drive the zig they were tested with, whatever else is on PATH
# when they run. (The modulefile still depends_on that zig, so `zig` itself
# is there for the user too.)
ZIG=$(command -v zig)

mkdir -p downloaded/bin

# shim <name> <zig subcommand> [fixed flags...]
shim()
{
    local name=$1
    shift
    cat > "downloaded/bin/${name}" <<SHIM
#!/bin/sh
# ${name} -> zig $* -- generated by the cc module (cc/sm-config/install.sh)
exec "${ZIG}" $* "\$@"
SHIM
    chmod 0755 "downloaded/bin/${name}"
}

# -fno-sanitize=undefined: `zig cc` compiles with UBSan in trap mode unless an
# optimisation level says otherwise, so C with undefined behaviour dies with
# an illegal instruction (or a zig panic) where gcc would have carried on.
# gcc's semantics are what people expect from a `cc`. The flag comes before
# the user's arguments, so an explicit -fsanitize=... still wins.
FIXED="-target ${TARGET} -fno-sanitize=undefined"

shim cc      cc  ${FIXED}
shim gcc     cc  ${FIXED}
shim c++     c++ ${FIXED}
shim g++     c++ ${FIXED}
shim ar      ar
shim ranlib  ranlib
shim objcopy objcopy
# zig exposes lld's ELF driver; on macOS it links Mach-O itself and there is
# no ld64.lld subcommand to wrap
if [[ ${OS} == "linux" ]]
then
    shim ld ld.lld
fi

# cc-target: the target the shims use, for anyone driving zig directly
# (`zig build-exe -target $(cc-target) ...`) and for recipes that build on
# this module (cargo-zigbuild bakes it into its linker wrapper)
cat > downloaded/bin/cc-target <<TARGET_SCRIPT
#!/bin/sh
# prints the target triple every shim of this module passes to zig
echo "${TARGET}"
TARGET_SCRIPT
chmod 0755 downloaded/bin/cc-target

#______________________________________________________________________________
# Smoke test: compile, archive, link and -- where the build host can run them
# -- execute a C and a C++ program through the shims. zig's cache stays inside
# the staging directory, so the libc++ this builds is cleaned up with it.
#
export ZIG_GLOBAL_CACHE_DIR=$(pwd)/zig-cache
PATH="$(pwd)/downloaded/bin:${PATH}"

mkdir -p smoke
cat > smoke/hello.c <<'SRC'
#include <stdio.h>
int main(void) { printf("hello from C\n"); return 0; }
SRC
cat > smoke/hello.cpp <<'SRC'
#include <iostream>
#include <string>
#include <vector>
int main() {
    std::vector<std::string> words{"hello", "from", "C++"};
    for (const auto& w : words) std::cout << w << ' ';
    std::cout << std::endl;
    return 0;
}
SRC

echo "cc: smoke test for target $(cc-target)"
cc -O2 -c -o smoke/hello.o smoke/hello.c
ar rcs smoke/libhello.a smoke/hello.o
ranlib smoke/libhello.a
cc -O2 -o smoke/hello_c smoke/hello.o
# the first C++ compile builds libc++ into the cache and, with zig 0.16, prints
# a wall of libc++'s own -Wnullability-completeness warnings while doing so --
# keep them out of the log unless the compile actually fails
if ! c++ -O2 -o smoke/hello_cpp smoke/hello.cpp 2> smoke/c++.log
then
    cat smoke/c++.log
    echo "cc: C++ smoke test failed to compile"
    exit 1
fi

# The binaries target the fleet's glibc floor, not this host; only run them
# where the host qualifies (it always does on macOS)
can_run=1
if [[ ${OS} == "linux" ]]
then
    HOST_GLIBC=$(ldd --version 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9]+' | tail -1) || true
    if [[ -z ${HOST_GLIBC} ]] \
        || [[ $(printf '%s\n%s\n' "${GLIBC_FLOOR}" "${HOST_GLIBC}" | sort -V | head -1) != "${GLIBC_FLOOR}" ]]
    then
        echo "cc: this host's glibc (${HOST_GLIBC:-unknown}) is older than the ${GLIBC_FLOOR} floor -- not running the smoke test binaries here"
        can_run=0
    fi
fi
if (( can_run ))
then
    # capture, then grep: `| grep -q` would close the pipe on the first
    # match, and a SIGPIPE on the writer's side fails the pipeline
    smoke/hello_c   > smoke/c.out
    smoke/hello_cpp > smoke/c++.out
    grep -q '^hello from C$'  smoke/c.out
    grep -q '^hello from C++' smoke/c++.out
    echo "cc: smoke test binaries ran"
fi
#------------------------------------------------------------------------------
