#!/usr/bin/env fish
set -gx LMOD_ROOT /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod
set -gx LMOD_PKG  /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod
set -gx LMOD_DIR  /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod/libexec
set -gx LMOD_CMD  /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod/libexec/lmod

set -gx MODULESHOME /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod

set -gx LMOD_VERSION "9.2"

set -gx FPATH (/Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod/libexec/addto --append FPATH /Users/johannes.blaschke/Developer/cli-util-mods/opt/lmod/lmod/init/ksh_funcs)

if status -i
   function module
      eval $LMOD_CMD fish $argv | source -
   end
else
   function module
      eval $LMOD_CMD fish --no_redirect $argv | source -
   end
end

function ml
   eval $LMOD_DIR/ml_cmd $argv | source -
end
