module load uv

# One release tag of EIT-GBI/Lustre-DLM, verified against the pinned digest,
# with its frozen uv.lock (including the `usage` extra for DuckDB) in a venv
# on a uv-managed Python. Nothing is resolved at run time.
src="${INSTALL_ROOT}/src"
tarball="$(mktemp "${TMPDIR:-/tmp}/lustre-dlm-XXXXXX.tar.gz")"
trap 'rm -f "$tarball"' EXIT
curl -fsSL -o "$tarball" \
    "https://github.com/EIT-GBI/Lustre-DLM/archive/refs/tags/v${VERSION}.tar.gz"
echo "${LUSTRE_DLM_SHA256}  ${tarball}" | sha256sum -c -
rm -rf "$src"
mkdir -p "$src" "${INSTALL_ROOT}/bin"
tar -xzf "$tarball" -C "$src" --strip-components=1
grep -qx "version = \"${VERSION}\"" "$src/pyproject.toml"

UV_PROJECT_ENVIRONMENT="${INSTALL_ROOT}/venv" \
    uv sync --project "$src" --frozen --no-dev --extra usage --no-install-project
"${INSTALL_ROOT}/venv/bin/python" -c 'import duckdb, msgpack, qpipe'

# The production entrypoint: pins the interpreter and revision that
# stat_srun and the completion manifest use.
cat > "${INSTALL_ROOT}/bin/lustre-dlm-usage" <<WRAPPER
#!/bin/sh
# lustre-dlm-usage: Lustre-DLM ${VERSION} (${LUSTRE_DLM_COMMIT}) per-owner
# usage collection (generated by the lustre-dlm module recipe)
export LUSTRE_DLM_PYTHON="${INSTALL_ROOT}/venv/bin/python"
export LUSTRE_DLM_REVISION="${LUSTRE_DLM_COMMIT}"
exec "\$LUSTRE_DLM_PYTHON" "${src}/pipelines/run_usage.py" "\$@"
WRAPPER
chmod 0755 "${INSTALL_ROOT}/bin/lustre-dlm-usage"
"${INSTALL_ROOT}/bin/lustre-dlm-usage" --help >/dev/null
