[env]
SOURCE_NAME   = "nu-{INSTALL_VERSION}-{RUNTIME_TARGET_TRIPLE}"
SOURCE_PREFIX = "https://github.com/nushell/nushell/releases/download/{INSTALL_VERSION}"
VERSION       = "{INSTALL_VERSION}"
VARIANT       = "{INSTALL_VERSION_VARIANT}"

[install]
versions = ["0.115.0", "0.114.1"]
prefix = "{SITE_DESTINATION}/{STAGE_DIR}"
# note: this is Lua regex: you will need to escape - and + (using %)
format = "^downloaded$"
# (optional) relocate after install
destination = "{SITE_DESTINATION}/{INSTALL_VERSION_VARIANT}"
stage = true

[module]
PATH = "{INSTALL_DIR}"
LD_LIBRARY_PATH = "{INSTALL_DIR}"
INSTALL_VERSION = "{INSTALL_VERSION}"

[post]
# toggles mandatory relocate if `stage` and `clean` are true. If the install
# script already relocates the package, then we can set `safe = false`
safe = true
# delete staging aread after successful install
clean = true
