[constant]
# Used for versioning
template_version=1

# Keep the following templated parameters (will be "filled in" by SM later)
INSTALL_VERSION = "{{{INSTALL_VERSION}}}"
PATH = "{{{PATH}}}"
LD_LIBRARY_PATH = "{{{LD_LIBRARY_PATH}}}"

# This will be overwritten by CLI parameters during template rendering
name = "PLACEHOLDER"
version = "PLACEHOLDER"
source = "PLACEHOLDER"
ext = "PLACEHOLDER"
