module load uv
# for cc-target (the pinned zig target) -- and to make sure the module the
# modulefile depends on is actually there
module load cc/${CC_MODULE}

# `module load uv` points UV_TOOL_DIR / UV_TOOL_BIN_DIR at the uv module's own
# tree -- redirect them so the tool lands in this module's prefix instead
export UV_TOOL_DIR="${TOOL_DIR}"
export UV_TOOL_BIN_DIR="${TOOL_BIN_DIR}"

# `stable` installs whatever the latest PyPI release is; anything else is
# pinned. --reinstall makes re-running the recipe idempotent. The PyPI
# package is a prebuilt binary wheel -- installing through cargo instead
# would need a linker, which is the problem this tool solves.
if [[ ${VERSION} == "stable" ]]
then
    uv tool install --reinstall cargo-zigbuild
else
    uv tool install --reinstall cargo-zigbuild==${VERSION}
fi

# The wheel declares the `ziglang` PyPI package -- a 90MB second copy of zig
# -- as a dependency, for hosts that have no zig. cargo-zigbuild only falls
# back to it when no `zig` is on PATH, and with this module the cc module's
# zig always is: uninstall it from the tool's venv rather than ship it.
uv pip uninstall --python "${TOOL_DIR}/cargo-zigbuild/bin/python" ziglang

# Wrappers for plain `cargo build`, around cargo-zigbuild's patched `zig cc`
# driver -- the same thing `cargo zigbuild` generates for itself:
#   * zig-linker: rustc's link line is written for a GNU-flavoured cc
#     (-lgcc_s, -Wl,--as-needed, ...) and the driver rewrites it for zig; the
#     modulefile puts this behind CARGO_TARGET_<triple>_LINKER.
#   * zig-cc / zig-c++: the cc crate (build scripts that compile C or C++)
#     passes clang-style --target=<llvm triple> flags, which plain `zig cc`
#     rejects and the driver translates; the modulefile puts these behind
#     CC_<triple> / CXX_<triple>, which the cc crate prefers over CC/CXX.
# The cc module's target is baked into all three, so linking and compiling
# agree on the glibc floor (the driver keeps a -target it is given over a
# --target= it has to translate). -fno-sanitize=undefined for the same
# reason as in the cc module's shims: gcc semantics, no UBSan trap at -O0.
TARGET=$(cc-target)
wrapper()
{
    local name=$1 sub=$2
    shift 2
    cat > "${TOOL_BIN_DIR}/${name}" <<WRAPPER
#!/bin/sh
# ${name}: cargo-zigbuild's patched \`zig ${sub}\`, target ${TARGET}
# (generated by the cargo-zigbuild module recipe)
exec "${TOOL_BIN_DIR}/cargo-zigbuild" zig ${sub} -- -target ${TARGET} $* "\$@"
WRAPPER
    chmod 0755 "${TOOL_BIN_DIR}/${name}"
}
wrapper zig-linker cc
wrapper zig-cc     cc  -fno-sanitize=undefined
wrapper zig-c++    c++ -fno-sanitize=undefined

"${TOOL_BIN_DIR}/cargo-zigbuild" --version
